global:
  scrape_interval: 5s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
  - job_name: 'auth-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-server:9001']
  - job_name: 'catalog-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['catalog-service:8082']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']
  - job_name: 'checkout-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'checkout-service:8083']
  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'discovery-service:8761']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
